"""Flashcards — spec Prompt 6.

    POST   /flashcards/generate          domain_id, difficulty?, count?
    POST   /flashcards/import            module_id, name?, cards[]  (CSV import)
    GET    /flashcards/{domain_id}        all cards for a domain
    DELETE /flashcards/{card_id}
    PATCH  /flashcards/{card_id}/favourite

Cards are generated by Gemini from the domain's material and stored in Supabase.
Difficulty defaults to the caller's saved preference and can be overridden per
generation.

Flashcards can also be *imported* from a CSV (e.g. a Quizlet export) — parsed
client-side into question/answer rows and posted here directly, bypassing the
source-ingestion pipeline. An imported deck is stored as its own lightweight
domain so it shows in the Classroom tab exactly like a generated set.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, Field

from app.database import get_supabase
from app.services import performance, removal, schema_features
from app.routers.auth import AuthUser, get_current_user
from app.services.ai_service import (
    GenerationError,
    gather_domain_content,
    generate_flashcards,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/flashcards", tags=["flashcards"])


# --- Schemas ----------------------------------------------------------------
class GenerateRequest(BaseModel):
    domain_id: str
    difficulty: str | None = Field(
        None, description="easy | medium | hard. Defaults to your saved preference."
    )
    # The deck slider offers up to 500 across a module; the caller splits
    # that across domains, and generation batches internally.
    count: int = Field(10, ge=1, le=500)


class Flashcard(BaseModel):
    id: str
    domain_id: str | None = None
    module_id: str | None = None
    front: str
    back: str
    # Tappable vocabulary and acronyms found in this text, generated with it so
    # the definition popover opens with no round trip.
    terms: list[dict[str, Any]] = Field(default_factory=list)
    difficulty: str | None = None
    # Which deck this card was generated into. A domain holds several, so the
    # title is how a caller asks for one of them rather than all of them.
    deck_title: str = ""
    is_favourite: bool = False
    created_at: datetime | None = None


class ImportedCard(BaseModel):
    front: str = Field(..., min_length=1, max_length=4000)
    back: str = Field(..., min_length=1, max_length=4000)


# Support CSV files up to 1000 rows (spec). The frontend caps + warns; this is
# the server-side safety net.
MAX_IMPORT_CARDS = 1000


class ImportRequest(BaseModel):
    module_id: str
    name: str | None = Field(None, max_length=200)
    cards: list[ImportedCard] = Field(..., min_length=1, max_length=MAX_IMPORT_CARDS)


class ImportResult(BaseModel):
    domain_id: str
    domain_title: str
    count: int


# --- Helpers ----------------------------------------------------------------
def _client():
    try:
        return get_supabase()
    except RuntimeError as exc:
        raise HTTPException(status.HTTP_503_SERVICE_UNAVAILABLE, str(exc)) from exc


def _own_card(card_id: str, user_id: str) -> dict[str, Any]:
    rows = (
        _client().table("flashcards").select("*")
        .eq("id", card_id).eq("user_id", user_id).limit(1).execute()
    ).data or []
    if not rows:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Flashcard not found.")
    return rows[0]


def _preferred_difficulty(user_id: str) -> str:
    rows = (
        _client().table("profiles").select("preferences")
        .eq("id", user_id).limit(1).execute()
    ).data or []
    prefs = (rows[0].get("preferences") if rows else {}) or {}
    return prefs.get("flashcard_difficulty") or "medium"


def _to_card(row: dict[str, Any]) -> Flashcard:
    return Flashcard(
        id=row["id"],
        domain_id=row.get("domain_id"),
        module_id=row.get("module_id"),
        front=row.get("front") or "",
        back=row.get("back") or "",
        difficulty=row.get("difficulty"),
        deck_title=(row.get("deck_title") or "").strip(),
        is_favourite=bool(row.get("is_favourite")),
        created_at=row.get("created_at"),
    )


def _unique_deck_title(domain_id: str, user_id: str, wanted: str) -> str:
    """`wanted`, or `wanted (2)`, `wanted (3)`… if the domain already has it."""
    if not wanted or not schema_features.has_column("flashcards", "deck_title"):
        return wanted
    rows = (
        _client().table("flashcards").select("deck_title")
        .eq("domain_id", domain_id).eq("user_id", user_id).execute()
    ).data or []
    taken = {(r.get("deck_title") or "").strip() for r in rows}
    if wanted not in taken:
        return wanted
    n = 2
    while f"{wanted} ({n})" in taken:
        n += 1
    return f"{wanted} ({n})"[:120]


# --- Routes -----------------------------------------------------------------
@router.post("/generate", response_model=list[Flashcard],
             status_code=status.HTTP_201_CREATED)
def generate(
    payload: GenerateRequest,
    user: AuthUser = Depends(get_current_user),
) -> list[Flashcard]:
    """Generate and store a set of flashcards for a domain."""
    difficulty = (payload.difficulty or _preferred_difficulty(user.id)).lower()

    try:
        gathered = gather_domain_content(payload.domain_id, user.id)
    except GenerationError as exc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, str(exc)) from exc

    domain = gathered["domain"]
    try:
        cards = generate_flashcards(
            gathered["content"], difficulty, payload.count,
            subject=gathered["subject"], topic=domain.get("title") or "",
            # Weak domains get cards that rebuild the fundamentals; strong ones
            # get the edges. Same count, different deck.
            focus=performance.focus_hint(
                domain.get("module_id") or "", user.id, payload.domain_id,
            ) if domain.get("module_id") else "",
        )
    except GenerationError as exc:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY, str(exc)) from exc

    # Decks are grouped by title, so two batches that land on the same name
    # would read as one deck of forty rather than two of twenty. The model has
    # no way of knowing what it called the last one, so the collision is
    # resolved here — a suffix, not a refusal, because the name it chose is
    # still the best description of what the cards are about.
    deck_title = _unique_deck_title(
        payload.domain_id, user.id, (cards[0].get("deck_title") if cards else "") or "",
    )

    rows = [
        {
            "domain_id": payload.domain_id,
            "module_id": domain.get("module_id"),
            "user_id": user.id,
            "front": c["front"],
            "back": c["back"],
            "difficulty": difficulty,
            "terms": c.get("terms") or [],
            "deck_title": deck_title,
        }
        for c in cards
    ]
    rows = schema_features.strip_unsupported("flashcards", rows, "terms", "deck_title")
    inserted = _client().table("flashcards").insert(rows).execute()
    return [_to_card(r) for r in (inserted.data or [])]


@router.post("/import", response_model=ImportResult,
             status_code=status.HTTP_201_CREATED)
async def import_deck(
    payload: ImportRequest,
    user: AuthUser = Depends(get_current_user),
) -> ImportResult:
    """Import a flashcard deck from parsed CSV rows, bypassing the source
    pipeline.

    The deck is stored as its own lightweight domain (``status='locked'``,
    ``weight_pct=0``) so the module's bulk "Generate" actions and exam weighting
    skip it, while it still surfaces in the Classroom tab's flashcard list like
    any generated set. Cards map ``front`` = question, ``back`` = answer.
    """
    client = _client()

    # Ownership — the deck must attach to a module the caller owns.
    owns = (
        client.table("modules").select("id")
        .eq("id", payload.module_id).eq("user_id", user.id).limit(1).execute()
    ).data or []
    if not owns:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Module not found.")

    # Keep only rows with both sides present; the frontend trims, this is a guard.
    cards = [
        (c.front.strip(), c.back.strip())
        for c in payload.cards
        if c.front.strip() and c.back.strip()
    ][:MAX_IMPORT_CARDS]
    if not cards:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            "No rows with both a question and an answer were found.",
        )

    name = (payload.name or "").strip()[:200] or "Imported flashcards"

    # Sort the new deck after any existing domains.
    existing = (
        client.table("domains").select("order_index")
        .eq("module_id", payload.module_id).eq("user_id", user.id).execute()
    ).data or []
    next_index = max((d.get("order_index") or 0 for d in existing), default=0) + 1

    domain_ins = client.table("domains").insert({
        "module_id": payload.module_id,
        "user_id": user.id,
        "title": name,
        "description": "Imported flashcard deck",
        "status": "unlocked",
        # Not a blueprint domain: skipped by bulk generate, exam weighting and
        # domain assignment. This used to ride on status='locked', which also
        # meant "not earned yet" — one flag, two unrelated jobs.
        "is_deck": True,
        "weight_pct": 0,
        "order_index": next_index,
    }).execute()
    if not domain_ins.data:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY,
                            "Could not create the imported deck.")
    domain_id = domain_ins.data[0]["id"]

    rows = [
        {
            "domain_id": domain_id,
            "module_id": payload.module_id,
            "user_id": user.id,
            "front": front,
            "back": back,
        }
        for front, back in cards
    ]
    # The domain was created to hold these cards. If they do not land it is not
    # an empty deck, it is a heading with nothing under it and no way to fill
    # it — so it goes back too.
    try:
        written = (client.table("flashcards").insert(rows).execute()).data
    except Exception:
        written = None
    if not written:
        client.table("domains").delete().eq("id", domain_id).execute()
        raise HTTPException(
            status.HTTP_502_BAD_GATEWAY,
            "Could not save those cards — nothing was imported.",
        )

    return ImportResult(domain_id=domain_id, domain_title=name, count=len(rows))


@router.delete("/deck/{domain_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_deck(
    domain_id: str,
    deck: str | None = Query(
        None,
        description="Which deck of this domain. Omit for every card it holds.",
    ),
    user: AuthUser = Depends(get_current_user),
) -> None:
    """Remove a deck from the learner's screens.

    Cards have no deck row of their own, so a deck is "this domain's cards with
    this title" — and without a title, all of them, which is what this meant
    when a domain could only hold one. The domain itself stays either way,
    since it may carry lectures and quizzes.

    The cards are marked rather than deleted. A card the learner got wrong is
    already in the missed container as a snapshot, but `study_attempts` and
    `review_later` are polymorphic with no foreign key, so deleting the row
    leaves them pointing at nothing — and per-card outcomes are how flashcards
    feed domain strength at all.
    """
    client = _client()
    scoped = client.table("flashcards").select("id").eq(
        "domain_id", domain_id
    ).eq("user_id", user.id)
    if deck is not None and schema_features.has_column("flashcards", "deck_title"):
        scoped = scoped.eq("deck_title", deck)
    if not removal.live(scoped, "flashcards").limit(1).execute().data:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "No deck to remove.")

    write = client.table("flashcards")
    write = (
        write.update(removal.stamp()) if removal.supported("flashcards")
        else write.delete()
    )
    write = write.eq("domain_id", domain_id).eq("user_id", user.id)
    if deck is not None and schema_features.has_column("flashcards", "deck_title"):
        write = write.eq("deck_title", deck)
    write.execute()


@router.get("/{domain_id}", response_model=list[Flashcard])
async def list_for_domain(
    domain_id: str,
    favourites_only: bool = Query(False),
    user: AuthUser = Depends(get_current_user),
) -> list[Flashcard]:
    """All flashcards for a domain, newest first."""
    query = (
        removal.live(_client().table("flashcards").select("*"), "flashcards")
        .eq("domain_id", domain_id).eq("user_id", user.id)
    )
    if favourites_only:
        query = query.eq("is_favourite", True)
    rows = (query.order("created_at", desc=True).execute()).data or []
    return [_to_card(r) for r in rows]


@router.patch("/{card_id}/favourite", response_model=Flashcard)
async def toggle_favourite(
    card_id: str,
    user: AuthUser = Depends(get_current_user),
) -> Flashcard:
    """Toggle a card's favourite flag."""
    card = _own_card(card_id, user.id)
    updated = (
        _client().table("flashcards")
        .update({"is_favourite": not bool(card.get("is_favourite"))})
        .eq("id", card_id).eq("user_id", user.id).execute()
    )
    if not updated.data:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Flashcard not found.")
    return _to_card(updated.data[0])


@router.delete("/{card_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_card(
    card_id: str,
    user: AuthUser = Depends(get_current_user),
) -> None:
    """Delete a flashcard."""
    _own_card(card_id, user.id)
    _client().table("flashcards").delete().eq("id", card_id).eq(
        "user_id", user.id
    ).execute()
