"""Flashcards — spec Prompt 6.

    POST   /flashcards/generate          domain_id, difficulty?, count?
    GET    /flashcards/{domain_id}        all cards for a domain
    DELETE /flashcards/{card_id}
    PATCH  /flashcards/{card_id}/favourite

Cards are generated by Gemini from the domain's material and stored in Supabase.
Difficulty defaults to the caller's saved preference and can be overridden per
generation.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, Field

from app.database import get_supabase
from app.routers.auth import AuthUser, get_current_user
from app.services.ai_service import (
    GenerationError,
    gather_domain_content,
    generate_flashcards,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/flashcards", tags=["flashcards"])


# --- Schemas ----------------------------------------------------------------
class GenerateRequest(BaseModel):
    domain_id: str
    difficulty: str | None = Field(
        None, description="easy | medium | hard. Defaults to your saved preference."
    )
    count: int = Field(10, ge=1, le=30)


class Flashcard(BaseModel):
    id: str
    domain_id: str | None = None
    module_id: str | None = None
    front: str
    back: str
    difficulty: str | None = None
    is_favourite: bool = False
    created_at: datetime | None = None


# --- Helpers ----------------------------------------------------------------
def _client():
    try:
        return get_supabase()
    except RuntimeError as exc:
        raise HTTPException(status.HTTP_503_SERVICE_UNAVAILABLE, str(exc)) from exc


def _own_card(card_id: str, user_id: str) -> dict[str, Any]:
    rows = (
        _client().table("flashcards").select("*")
        .eq("id", card_id).eq("user_id", user_id).limit(1).execute()
    ).data or []
    if not rows:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Flashcard not found.")
    return rows[0]


def _preferred_difficulty(user_id: str) -> str:
    rows = (
        _client().table("profiles").select("preferences")
        .eq("id", user_id).limit(1).execute()
    ).data or []
    prefs = (rows[0].get("preferences") if rows else {}) or {}
    return prefs.get("flashcard_difficulty") or "medium"


def _to_card(row: dict[str, Any]) -> Flashcard:
    return Flashcard(
        id=row["id"],
        domain_id=row.get("domain_id"),
        module_id=row.get("module_id"),
        front=row.get("front") or "",
        back=row.get("back") or "",
        difficulty=row.get("difficulty"),
        is_favourite=bool(row.get("is_favourite")),
        created_at=row.get("created_at"),
    )


# --- Routes -----------------------------------------------------------------
@router.post("/generate", response_model=list[Flashcard],
             status_code=status.HTTP_201_CREATED)
async def generate(
    payload: GenerateRequest,
    user: AuthUser = Depends(get_current_user),
) -> list[Flashcard]:
    """Generate and store a set of flashcards for a domain."""
    difficulty = (payload.difficulty or _preferred_difficulty(user.id)).lower()

    try:
        gathered = gather_domain_content(payload.domain_id, user.id)
    except GenerationError as exc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, str(exc)) from exc

    domain = gathered["domain"]
    try:
        cards = generate_flashcards(
            gathered["content"], difficulty, payload.count,
            subject=gathered["subject"], topic=domain.get("title") or "",
        )
    except GenerationError as exc:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY, str(exc)) from exc

    rows = [
        {
            "domain_id": payload.domain_id,
            "module_id": domain.get("module_id"),
            "user_id": user.id,
            "front": c["front"],
            "back": c["back"],
            "difficulty": difficulty,
        }
        for c in cards
    ]
    inserted = _client().table("flashcards").insert(rows).execute()
    return [_to_card(r) for r in (inserted.data or [])]


@router.get("/{domain_id}", response_model=list[Flashcard])
async def list_for_domain(
    domain_id: str,
    favourites_only: bool = Query(False),
    user: AuthUser = Depends(get_current_user),
) -> list[Flashcard]:
    """All flashcards for a domain, newest first."""
    query = (
        _client().table("flashcards").select("*")
        .eq("domain_id", domain_id).eq("user_id", user.id)
    )
    if favourites_only:
        query = query.eq("is_favourite", True)
    rows = (query.order("created_at", desc=True).execute()).data or []
    return [_to_card(r) for r in rows]


@router.patch("/{card_id}/favourite", response_model=Flashcard)
async def toggle_favourite(
    card_id: str,
    user: AuthUser = Depends(get_current_user),
) -> Flashcard:
    """Toggle a card's favourite flag."""
    card = _own_card(card_id, user.id)
    updated = (
        _client().table("flashcards")
        .update({"is_favourite": not bool(card.get("is_favourite"))})
        .eq("id", card_id).eq("user_id", user.id).execute()
    )
    if not updated.data:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Flashcard not found.")
    return _to_card(updated.data[0])


@router.delete("/{card_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_card(
    card_id: str,
    user: AuthUser = Depends(get_current_user),
) -> None:
    """Delete a flashcard."""
    _own_card(card_id, user.id)
    _client().table("flashcards").delete().eq("id", card_id).eq(
        "user_id", user.id
    ).execute()
