"""Flashcards — spec Prompt 6.

    POST   /flashcards/generate          domain_id, difficulty?, count?
    POST   /flashcards/import            module_id, name?, cards[]  (CSV import)
    GET    /flashcards/{domain_id}        all cards for a domain
    DELETE /flashcards/{card_id}
    PATCH  /flashcards/{card_id}/favourite

Cards are generated by Gemini from the domain's material and stored in Supabase.
Difficulty defaults to the caller's saved preference and can be overridden per
generation.

Flashcards can also be *imported* from a CSV (e.g. a Quizlet export) — parsed
client-side into question/answer rows and posted here directly, bypassing the
source-ingestion pipeline. An imported deck is stored as its own lightweight
domain so it shows in the Classroom tab exactly like a generated set.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, Field

from app.database import get_supabase
from app.services import schema_features
from app.routers.auth import AuthUser, get_current_user
from app.services.ai_service import (
    GenerationError,
    gather_domain_content,
    generate_flashcards,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/flashcards", tags=["flashcards"])


# --- Schemas ----------------------------------------------------------------
class GenerateRequest(BaseModel):
    domain_id: str
    difficulty: str | None = Field(
        None, description="easy | medium | hard. Defaults to your saved preference."
    )
    # The deck slider offers up to 500 across a module; the caller splits
    # that across domains, and generation batches internally.
    count: int = Field(10, ge=1, le=500)


class Flashcard(BaseModel):
    id: str
    domain_id: str | None = None
    module_id: str | None = None
    front: str
    back: str
    # Tappable vocabulary and acronyms found in this text, generated with it so
    # the definition popover opens with no round trip.
    terms: list[dict[str, Any]] = Field(default_factory=list)
    difficulty: str | None = None
    is_favourite: bool = False
    created_at: datetime | None = None


class ImportedCard(BaseModel):
    front: str = Field(..., min_length=1, max_length=4000)
    back: str = Field(..., min_length=1, max_length=4000)


# Support CSV files up to 1000 rows (spec). The frontend caps + warns; this is
# the server-side safety net.
MAX_IMPORT_CARDS = 1000


class ImportRequest(BaseModel):
    module_id: str
    name: str | None = Field(None, max_length=200)
    cards: list[ImportedCard] = Field(..., min_length=1, max_length=MAX_IMPORT_CARDS)


class ImportResult(BaseModel):
    domain_id: str
    domain_title: str
    count: int


# --- Helpers ----------------------------------------------------------------
def _client():
    try:
        return get_supabase()
    except RuntimeError as exc:
        raise HTTPException(status.HTTP_503_SERVICE_UNAVAILABLE, str(exc)) from exc


def _own_card(card_id: str, user_id: str) -> dict[str, Any]:
    rows = (
        _client().table("flashcards").select("*")
        .eq("id", card_id).eq("user_id", user_id).limit(1).execute()
    ).data or []
    if not rows:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Flashcard not found.")
    return rows[0]


def _preferred_difficulty(user_id: str) -> str:
    rows = (
        _client().table("profiles").select("preferences")
        .eq("id", user_id).limit(1).execute()
    ).data or []
    prefs = (rows[0].get("preferences") if rows else {}) or {}
    return prefs.get("flashcard_difficulty") or "medium"


def _to_card(row: dict[str, Any]) -> Flashcard:
    return Flashcard(
        id=row["id"],
        domain_id=row.get("domain_id"),
        module_id=row.get("module_id"),
        front=row.get("front") or "",
        back=row.get("back") or "",
        difficulty=row.get("difficulty"),
        is_favourite=bool(row.get("is_favourite")),
        created_at=row.get("created_at"),
    )


# --- Routes -----------------------------------------------------------------
@router.post("/generate", response_model=list[Flashcard],
             status_code=status.HTTP_201_CREATED)
async def generate(
    payload: GenerateRequest,
    user: AuthUser = Depends(get_current_user),
) -> list[Flashcard]:
    """Generate and store a set of flashcards for a domain."""
    difficulty = (payload.difficulty or _preferred_difficulty(user.id)).lower()

    try:
        gathered = gather_domain_content(payload.domain_id, user.id)
    except GenerationError as exc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, str(exc)) from exc

    domain = gathered["domain"]
    try:
        cards = generate_flashcards(
            gathered["content"], difficulty, payload.count,
            subject=gathered["subject"], topic=domain.get("title") or "",
        )
    except GenerationError as exc:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY, str(exc)) from exc

    rows = [
        {
            "domain_id": payload.domain_id,
            "module_id": domain.get("module_id"),
            "user_id": user.id,
            "front": c["front"],
            "back": c["back"],
            "difficulty": difficulty,
            "terms": c.get("terms") or [],
        }
        for c in cards
    ]
    rows = schema_features.strip_unsupported("flashcards", rows, "terms")
    inserted = _client().table("flashcards").insert(rows).execute()
    return [_to_card(r) for r in (inserted.data or [])]


@router.post("/import", response_model=ImportResult,
             status_code=status.HTTP_201_CREATED)
async def import_deck(
    payload: ImportRequest,
    user: AuthUser = Depends(get_current_user),
) -> ImportResult:
    """Import a flashcard deck from parsed CSV rows, bypassing the source
    pipeline.

    The deck is stored as its own lightweight domain (``status='locked'``,
    ``weight_pct=0``) so the module's bulk "Generate" actions and exam weighting
    skip it, while it still surfaces in the Classroom tab's flashcard list like
    any generated set. Cards map ``front`` = question, ``back`` = answer.
    """
    client = _client()

    # Ownership — the deck must attach to a module the caller owns.
    owns = (
        client.table("modules").select("id")
        .eq("id", payload.module_id).eq("user_id", user.id).limit(1).execute()
    ).data or []
    if not owns:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Module not found.")

    # Keep only rows with both sides present; the frontend trims, this is a guard.
    cards = [
        (c.front.strip(), c.back.strip())
        for c in payload.cards
        if c.front.strip() and c.back.strip()
    ][:MAX_IMPORT_CARDS]
    if not cards:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            "No rows with both a question and an answer were found.",
        )

    name = (payload.name or "").strip()[:200] or "Imported flashcards"

    # Sort the new deck after any existing domains.
    existing = (
        client.table("domains").select("order_index")
        .eq("module_id", payload.module_id).eq("user_id", user.id).execute()
    ).data or []
    next_index = max((d.get("order_index") or 0 for d in existing), default=0) + 1

    domain_ins = client.table("domains").insert({
        "module_id": payload.module_id,
        "user_id": user.id,
        "title": name,
        "description": "Imported flashcard deck",
        "status": "locked",  # skipped by bulk generate + exam weighting
        "weight_pct": 0,
        "order_index": next_index,
    }).execute()
    if not domain_ins.data:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY,
                            "Could not create the imported deck.")
    domain_id = domain_ins.data[0]["id"]

    rows = [
        {
            "domain_id": domain_id,
            "module_id": payload.module_id,
            "user_id": user.id,
            "front": front,
            "back": back,
        }
        for front, back in cards
    ]
    client.table("flashcards").insert(rows).execute()

    return ImportResult(domain_id=domain_id, domain_title=name, count=len(rows))


@router.get("/{domain_id}", response_model=list[Flashcard])
async def list_for_domain(
    domain_id: str,
    favourites_only: bool = Query(False),
    user: AuthUser = Depends(get_current_user),
) -> list[Flashcard]:
    """All flashcards for a domain, newest first."""
    query = (
        _client().table("flashcards").select("*")
        .eq("domain_id", domain_id).eq("user_id", user.id)
    )
    if favourites_only:
        query = query.eq("is_favourite", True)
    rows = (query.order("created_at", desc=True).execute()).data or []
    return [_to_card(r) for r in rows]


@router.patch("/{card_id}/favourite", response_model=Flashcard)
async def toggle_favourite(
    card_id: str,
    user: AuthUser = Depends(get_current_user),
) -> Flashcard:
    """Toggle a card's favourite flag."""
    card = _own_card(card_id, user.id)
    updated = (
        _client().table("flashcards")
        .update({"is_favourite": not bool(card.get("is_favourite"))})
        .eq("id", card_id).eq("user_id", user.id).execute()
    )
    if not updated.data:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Flashcard not found.")
    return _to_card(updated.data[0])


@router.delete("/{card_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_card(
    card_id: str,
    user: AuthUser = Depends(get_current_user),
) -> None:
    """Delete a flashcard."""
    _own_card(card_id, user.id)
    _client().table("flashcards").delete().eq("id", card_id).eq(
        "user_id", user.id
    ).execute()
