"""Multiple-choice quizzes — spec Prompt 6.

    POST   /quizzes/generate            domain_id, difficulty?, question_count?
    GET    /quizzes/{domain_id}          quizzes for a domain (questions, no answers)
    POST   /quizzes/{quiz_id}/submit     grade an attempt, store the score
    DELETE /quizzes/{quiz_id}
    PATCH  /quizzes/{quiz_id}/favourite

Questions are generated by Gemini and stored as JSON on the quiz row. This is a
study quiz, not a proctored exam, so the correct answer and explanation are
included when the quiz is fetched — the runner shows immediate per-question
feedback. Grading is still done server-side against the stored answers so the
recorded score is authoritative.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field

from app.database import get_supabase
from app.routers.auth import AuthUser, get_current_user
from app.services.ai_service import (
    GenerationError,
    gather_domain_content,
    generate_quiz,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/quizzes", tags=["quizzes"])


# --- Schemas ----------------------------------------------------------------
class GenerateRequest(BaseModel):
    domain_id: str
    difficulty: str | None = Field(
        None, description="easy | medium | hard. Defaults to your saved preference."
    )
    question_count: int = Field(5, ge=1, le=20)


class Question(BaseModel):
    index: int
    question: str
    options: list[str]
    correct_index: int
    explanation: str = ""


class Quiz(BaseModel):
    id: str
    domain_id: str | None = None
    module_id: str | None = None
    title: str = "Quiz"
    difficulty: str | None = None
    question_count: int = 0
    questions: list[Question] = Field(default_factory=list)
    score: float | None = None
    is_favourite: bool = False
    created_at: datetime | None = None


class SubmitRequest(BaseModel):
    # answers[i] = the option index the learner chose for question i (or -1/None
    # if skipped).
    answers: list[int | None]


class QuestionResult(BaseModel):
    index: int
    chosen_index: int | None
    correct_index: int
    is_correct: bool
    explanation: str = ""


class SubmitResponse(BaseModel):
    quiz_id: str
    score: float          # percentage 0-100
    correct: int
    total: int
    results: list[QuestionResult]


# --- Helpers ----------------------------------------------------------------
def _client():
    try:
        return get_supabase()
    except RuntimeError as exc:
        raise HTTPException(status.HTTP_503_SERVICE_UNAVAILABLE, str(exc)) from exc


def _own_quiz(quiz_id: str, user_id: str) -> dict[str, Any]:
    rows = (
        _client().table("quizzes").select("*")
        .eq("id", quiz_id).eq("user_id", user_id).limit(1).execute()
    ).data or []
    if not rows:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Quiz not found.")
    return rows[0]


def _preferred_difficulty(user_id: str) -> str:
    rows = (
        _client().table("profiles").select("preferences")
        .eq("id", user_id).limit(1).execute()
    ).data or []
    prefs = (rows[0].get("preferences") if rows else {}) or {}
    return prefs.get("quiz_difficulty") or "medium"


def _questions(row: dict[str, Any]) -> list[dict[str, Any]]:
    return row.get("questions") or []


def _to_quiz(row: dict[str, Any]) -> Quiz:
    questions = [
        Question(
            index=i,
            question=q.get("question") or "",
            options=q.get("options") or [],
            correct_index=int(q.get("correct_index", 0)),
            explanation=q.get("explanation") or "",
        )
        for i, q in enumerate(_questions(row))
    ]
    return Quiz(
        id=row["id"],
        domain_id=row.get("domain_id"),
        module_id=row.get("module_id"),
        title=row.get("title") or "Quiz",
        difficulty=row.get("difficulty"),
        question_count=row.get("question_count") or len(questions),
        questions=questions,
        score=row.get("score"),
        is_favourite=bool(row.get("is_favourite")),
        created_at=row.get("created_at"),
    )


# --- Routes -----------------------------------------------------------------
@router.post("/generate", response_model=Quiz, status_code=status.HTTP_201_CREATED)
async def generate(
    payload: GenerateRequest,
    user: AuthUser = Depends(get_current_user),
) -> Quiz:
    """Generate and store a quiz for a domain."""
    difficulty = (payload.difficulty or _preferred_difficulty(user.id)).lower()

    try:
        gathered = gather_domain_content(payload.domain_id, user.id)
    except GenerationError as exc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, str(exc)) from exc

    domain = gathered["domain"]
    try:
        questions = generate_quiz(
            gathered["content"], difficulty, payload.question_count,
            subject=gathered["subject"], topic=domain.get("title") or "",
        )
    except GenerationError as exc:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY, str(exc)) from exc

    row = {
        "domain_id": payload.domain_id,
        "module_id": domain.get("module_id"),
        "user_id": user.id,
        "title": f"{domain.get('title') or 'Quiz'} — {difficulty}",
        "difficulty": difficulty,
        "question_count": len(questions),
        "questions": questions,
    }
    inserted = _client().table("quizzes").insert(row).execute()
    if not inserted.data:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY, "Could not save the quiz.")
    return _to_quiz(inserted.data[0])


@router.get("/{domain_id}", response_model=list[Quiz])
async def list_for_domain(
    domain_id: str,
    user: AuthUser = Depends(get_current_user),
) -> list[Quiz]:
    """Quizzes for a domain, newest first."""
    rows = (
        _client().table("quizzes").select("*")
        .eq("domain_id", domain_id).eq("user_id", user.id)
        .order("created_at", desc=True).execute()
    ).data or []
    return [_to_quiz(r) for r in rows]


@router.post("/{quiz_id}/submit", response_model=SubmitResponse)
async def submit(
    quiz_id: str,
    payload: SubmitRequest,
    user: AuthUser = Depends(get_current_user),
) -> SubmitResponse:
    """Grade an attempt against the stored answers and record the score."""
    quiz = _own_quiz(quiz_id, user.id)
    questions = _questions(quiz)
    if not questions:
        raise HTTPException(status.HTTP_409_CONFLICT, "This quiz has no questions.")

    results: list[QuestionResult] = []
    correct = 0
    for i, q in enumerate(questions):
        chosen = payload.answers[i] if i < len(payload.answers) else None
        correct_index = int(q.get("correct_index", 0))
        is_correct = chosen == correct_index
        correct += int(is_correct)
        results.append(QuestionResult(
            index=i,
            chosen_index=chosen,
            correct_index=correct_index,
            is_correct=is_correct,
            explanation=q.get("explanation") or "",
        ))

    total = len(questions)
    score = round(correct / total * 100, 1) if total else 0.0

    # Store the latest score on the quiz row (the schema keeps one score).
    _client().table("quizzes").update({"score": score}).eq("id", quiz_id).eq(
        "user_id", user.id
    ).execute()

    return SubmitResponse(
        quiz_id=quiz_id, score=score, correct=correct, total=total, results=results,
    )


@router.patch("/{quiz_id}/favourite", response_model=Quiz)
async def toggle_favourite(
    quiz_id: str,
    user: AuthUser = Depends(get_current_user),
) -> Quiz:
    """Toggle a quiz's favourite flag."""
    quiz = _own_quiz(quiz_id, user.id)
    updated = (
        _client().table("quizzes")
        .update({"is_favourite": not bool(quiz.get("is_favourite"))})
        .eq("id", quiz_id).eq("user_id", user.id).execute()
    )
    if not updated.data:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Quiz not found.")
    return _to_quiz(updated.data[0])


@router.delete("/{quiz_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_quiz(
    quiz_id: str,
    user: AuthUser = Depends(get_current_user),
) -> None:
    """Delete a quiz."""
    _own_quiz(quiz_id, user.id)
    _client().table("quizzes").delete().eq("id", quiz_id).eq(
        "user_id", user.id
    ).execute()
