"""Multiple-choice quizzes — spec Prompt 6.

    POST   /quizzes/generate            domain_id, difficulty?, question_count?
    GET    /quizzes/{domain_id}          quizzes for a domain (questions, no answers)
    POST   /quizzes/{quiz_id}/submit     grade an attempt, store the score
    DELETE /quizzes/{quiz_id}
    PATCH  /quizzes/{quiz_id}/favourite

Questions are generated by Gemini and stored as JSON on the quiz row. This is a
study quiz, not a proctored exam, so the correct answer and explanation are
included when the quiz is fetched — the runner shows immediate per-question
feedback. Grading is still done server-side against the stored answers so the
recorded score is authoritative.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field

from app.database import get_supabase
from app.routers.auth import AuthUser, get_current_user
from app.services import grading, performance, removal
from app.services.ai_service import (
    GenerationError,
    gather_domain_content,
    generate_quiz,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/quizzes", tags=["quizzes"])


# --- Schemas ----------------------------------------------------------------
class GenerateRequest(BaseModel):
    domain_id: str
    difficulty: str | None = Field(
        None, description="easy | medium | hard. Defaults to your saved preference."
    )
    question_count: int = Field(5, ge=1, le=100)


class Question(BaseModel):
    index: int
    question: str
    # 'mcq' | 'multi' | 'short' | 'blank'. A quiz ships its whole key — that
    # is the study-quiz trade — so multi-select's correct set and short
    # answer's accepted list ride along too; the fourth field Pydantic would
    # otherwise have silently dropped.
    kind: str = "mcq"
    correct_indices: list[int] = Field(default_factory=list)
    accepted: list[str] = Field(default_factory=list)
    # Which container entry this came from, for a quiz generated out of the
    # missed pool. Undeclared, Pydantic dropped it on the way out — so the
    # client never saw it, the session record carried nothing, and
    # auto-graduation could not fire for a container quiz at all. The same
    # class of silence as `SessionResult.bank_entry_id`.
    bank_entry_id: str | None = None
    # The quiz's domain, stamped onto every question.
    #
    # A question in a quiz has no domain of its own — the quiz has one, and the
    # questions belong to it. Undeclared, every result banked from a quiz went
    # into the missed pool with `domain_id` null, so "drill what I missed in
    # this domain" could never find any of it.
    domain_id: str | None = None
    options: list[str]
    correct_index: int
    explanation: str = ""
    # Why each option is right or wrong, positionally aligned with `options`.
    option_explanations: list[str] = Field(default_factory=list)
    # Tappable vocabulary and acronyms in this question, generated with it so
    # the definition popover opens with no round trip. Quizzes store their whole
    # question list as jsonb, so these ride along with no schema change.
    terms: list[dict[str, Any]] = Field(default_factory=list)


class Quiz(BaseModel):
    id: str
    domain_id: str | None = None
    module_id: str | None = None
    title: str = "Quiz"
    difficulty: str | None = None
    question_count: int = 0
    questions: list[Question] = Field(default_factory=list)
    score: float | None = None
    is_favourite: bool = False
    created_at: datetime | None = None


class SubmitRequest(BaseModel):
    # answers[i] is whatever the question's kind calls an answer: an option
    # index for multiple choice, a list of indices for multi-select, the typed
    # text for short answer and fill-in-the-blank. None where skipped.
    answers: list[int | list[int] | str | None]


class QuestionResult(BaseModel):
    index: int
    chosen_index: int | None
    correct_index: int
    is_correct: bool
    explanation: str = ""


class SubmitResponse(BaseModel):
    quiz_id: str
    score: float          # percentage 0-100
    correct: int
    total: int
    results: list[QuestionResult]


# --- Helpers ----------------------------------------------------------------
def _client():
    try:
        return get_supabase()
    except RuntimeError as exc:
        raise HTTPException(status.HTTP_503_SERVICE_UNAVAILABLE, str(exc)) from exc


def _own_quiz(quiz_id: str, user_id: str) -> dict[str, Any]:
    rows = (
        _client().table("quizzes").select("*")
        .eq("id", quiz_id).eq("user_id", user_id).limit(1).execute()
    ).data or []
    if not rows:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Quiz not found.")
    return rows[0]


def _preferred_difficulty(user_id: str) -> str:
    rows = (
        _client().table("profiles").select("preferences")
        .eq("id", user_id).limit(1).execute()
    ).data or []
    prefs = (rows[0].get("preferences") if rows else {}) or {}
    return prefs.get("quiz_difficulty") or "medium"


def _questions(row: dict[str, Any]) -> list[dict[str, Any]]:
    return row.get("questions") or []


def _to_quiz(row: dict[str, Any]) -> Quiz:
    questions = [
        Question(
            index=i,
            question=q.get("question") or q.get("prompt") or "",
            kind=q.get("kind") or "mcq",
            correct_indices=q.get("correct_indices") or [],
            accepted=q.get("accepted") or [],
            bank_entry_id=q.get("bank_entry_id"),
            domain_id=q.get("domain_id") or row.get("domain_id"),
            options=q.get("options") or [],
            correct_index=int(q.get("correct_index", 0)),
            explanation=q.get("explanation") or "",
            option_explanations=q.get("option_explanations") or [],
            terms=q.get("terms") or [],
        )
        for i, q in enumerate(_questions(row))
    ]
    return Quiz(
        id=row["id"],
        domain_id=row.get("domain_id"),
        module_id=row.get("module_id"),
        title=row.get("title") or "Quiz",
        difficulty=row.get("difficulty"),
        question_count=row.get("question_count") or len(questions),
        questions=questions,
        score=row.get("score"),
        is_favourite=bool(row.get("is_favourite")),
        created_at=row.get("created_at"),
    )


# --- Routes -----------------------------------------------------------------
@router.post("/generate", response_model=Quiz, status_code=status.HTTP_201_CREATED)
def generate(
    payload: GenerateRequest,
    user: AuthUser = Depends(get_current_user),
) -> Quiz:
    """Generate and store a quiz for a domain."""
    difficulty = (payload.difficulty or _preferred_difficulty(user.id)).lower()

    try:
        gathered = gather_domain_content(payload.domain_id, user.id)
    except GenerationError as exc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, str(exc)) from exc

    domain = gathered["domain"]
    try:
        questions = generate_quiz(
            gathered["content"], difficulty, payload.question_count,
            subject=gathered["subject"], topic=domain.get("title") or "",
            # What this learner's own results say about this domain. Weakness
            # changes what gets asked, not just how many questions arrive.
            focus=performance.focus_hint(
                domain.get("module_id") or "", user.id, payload.domain_id,
            ) if domain.get("module_id") else "",
        )
    except GenerationError as exc:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY, str(exc)) from exc

    row = {
        "domain_id": payload.domain_id,
        "module_id": domain.get("module_id"),
        "user_id": user.id,
        # The model names the quiz after what it actually covers; the domain
        # and difficulty are the fallback when it doesn't.
        "title": (questions[0].get("quiz_title") or "").strip()
        or f"{domain.get('title') or 'Quiz'} — {difficulty}",
        "difficulty": difficulty,
        "question_count": len(questions),
        "questions": questions,
    }
    inserted = _client().table("quizzes").insert(row).execute()
    if not inserted.data:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY, "Could not save the quiz.")
    return _to_quiz(inserted.data[0])


@router.get("/one/{quiz_id}", response_model=Quiz)
async def get_one(
    quiz_id: str,
    user: AuthUser = Depends(get_current_user),
) -> Quiz:
    """One quiz, by its own id.

    Every other way in is keyed by domain, which is right for a quiz about a
    domain and impossible for one generated from a container — its questions
    come from every domain at once, so it has no domain to be listed under.
    Declared above `/{domain_id}` so the literal path wins the match.
    """
    return _to_quiz(_own_quiz(quiz_id, user.id))


@router.get("/{domain_id}", response_model=list[Quiz])
async def list_for_domain(
    domain_id: str,
    user: AuthUser = Depends(get_current_user),
) -> list[Quiz]:
    """Quizzes for a domain, newest first."""
    rows = (
        removal.live(_client().table("quizzes").select("*"), "quizzes")
        .eq("domain_id", domain_id).eq("user_id", user.id)
        .order("created_at", desc=True).execute()
    ).data or []
    return [_to_quiz(r) for r in rows]


@router.post("/{quiz_id}/submit", response_model=SubmitResponse)
async def submit(
    quiz_id: str,
    payload: SubmitRequest,
    user: AuthUser = Depends(get_current_user),
) -> SubmitResponse:
    """Grade an attempt against the stored answers and record the score."""
    quiz = _own_quiz(quiz_id, user.id)
    questions = _questions(quiz)
    if not questions:
        raise HTTPException(status.HTTP_409_CONFLICT, "This quiz has no questions.")

    # Same rule as exams: a quiz score feeds domain strength, and a paper with
    # nothing answered is a peek, not a sitting.
    if not any(a is not None for a in payload.answers):
        raise HTTPException(
            status.HTTP_409_CONFLICT,
            "Nothing was answered, so this quiz wasn't graded or recorded.",
        )

    results: list[QuestionResult] = []
    correct = 0
    for i, q in enumerate(questions):
        chosen = payload.answers[i] if i < len(payload.answers) else None
        # One grader for every question kind, shared with exams and practice
        # mode — see services/grading for why it must not be three.
        is_correct = grading.grade(q, chosen)
        correct += int(is_correct)
        results.append(QuestionResult(
            index=i,
            chosen_index=chosen if isinstance(chosen, int) else None,
            correct_index=int(q.get("correct_index") or 0),
            is_correct=is_correct,
            explanation=q.get("explanation") or "",
        ))

    total = len(questions)
    score = round(correct / total * 100, 1) if total else 0.0

    # Store the latest score on the quiz row (the schema keeps one score).
    _client().table("quizzes").update({"score": score}).eq("id", quiz_id).eq(
        "user_id", user.id
    ).execute()

    return SubmitResponse(
        quiz_id=quiz_id, score=score, correct=correct, total=total, results=results,
    )


@router.patch("/{quiz_id}/favourite", response_model=Quiz)
async def toggle_favourite(
    quiz_id: str,
    user: AuthUser = Depends(get_current_user),
) -> Quiz:
    """Toggle a quiz's favourite flag."""
    quiz = _own_quiz(quiz_id, user.id)
    updated = (
        _client().table("quizzes")
        .update({"is_favourite": not bool(quiz.get("is_favourite"))})
        .eq("id", quiz_id).eq("user_id", user.id).execute()
    )
    if not updated.data:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Quiz not found.")
    return _to_quiz(updated.data[0])


@router.delete("/{quiz_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_quiz(
    quiz_id: str,
    user: AuthUser = Depends(get_current_user),
) -> None:
    """Remove a quiz from the learner's screens.

    The row stays, and so does its score. A quiz score feeds the domain's
    strength, and a strength that moves when somebody tidies up their Classroom
    would be measuring housekeeping rather than learning. What the learner
    asked for was the pill gone.

    Deployments that have not run the migration yet still delete outright,
    which is what they did before — worse than the new behaviour, better than a
    button that silently does nothing.
    """
    _own_quiz(quiz_id, user.id)
    table = _client().table("quizzes")
    if removal.supported("quizzes"):
        table.update(removal.stamp()).eq("id", quiz_id).eq(
            "user_id", user.id
        ).execute()
    else:
        table.delete().eq("id", quiz_id).eq("user_id", user.id).execute()
