"""Lecture generation — spec §4.4.

Text is generated by Gemini and streamed as it arrives, then converted to audio
by OpenAI TTS HD and cached in Supabase Storage.

Two details drive the shape of this module:

* **TTS input is capped at ~4096 characters**, so a lecture is not one MP3 but
  an ordered set of chunk objects. They are split on sentence boundaries so a
  chunk never cuts mid-word, and stored under ``<user>/<lecture>/NNN.mp3``.
* **Streaming must survive a dropped connection.** Every delta is persisted to
  ``lectures.transcript`` as well as published to the live channel, so a
  reconnecting client replays from the database.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from typing import Any

from app.config import settings
from app.database import get_supabase
from app.services import broadcast
from app.services.domains import _generate, quota_hint
from app.services.personas import persona_for

logger = logging.getLogger(__name__)

# OpenAI caps TTS input at 4096 chars; leave headroom for the split to land on a
# sentence boundary.
TTS_CHUNK_CHARS = 3800

# Target lengths (spec Prompt 4: short ~5min, medium ~15min, long ~30min).
# Spoken delivery runs ~140 wpm, which sets both the word target and the audio
# duration. A 30-minute lecture is ~4,200 words and a large amount of TTS audio
# — see the note in generate_lecture about payload/cost.
LENGTHS: dict[str, dict[str, Any]] = {
    "short":  {"words": 700,  "label": "about 5 minutes"},
    "medium": {"words": 2100, "label": "about 15 minutes"},
    "long":   {"words": 4200, "label": "about 30 minutes"},
}

# Spec voices -> OpenAI voices, overridable per deployment.
VOICES = {
    "marcus": lambda: settings.openai_voice_marcus,
    "sophia": lambda: settings.openai_voice_sophia,
}

WORDS_PER_MINUTE = 140


class LectureGenerationError(RuntimeError):
    """A lecture could not be generated."""


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def resolve_voice(voice: str) -> str:
    """Map a spec voice name to the OpenAI voice id."""
    factory = VOICES.get((voice or "").lower())
    if not factory:
        raise LectureGenerationError(
            f"Unknown voice {voice!r}. Choose one of: {', '.join(VOICES)}."
        )
    return factory()


def _update(lecture_id: str, payload: dict[str, Any]) -> None:
    get_supabase().table("lectures").update(payload).eq("id", lecture_id).execute()


# --- Text generation --------------------------------------------------------
def _system_instruction(voice: str, length: str) -> str:
    """The tutor's character and delivery brief — the lecture system prompt.

    Passed as ``system_instruction`` (separate from the per-lecture task) so the
    persona governs the whole generation. This is where Marcus/Sophia are named
    and told to speak as themselves, matching the voice the audio is narrated in
    and the character used in mid-lecture Q&A.
    """
    persona = persona_for(voice)
    spec = LENGTHS[length]
    return (
        f"You are {persona['name']}, an expert tutor recording an audio lecture "
        f"for a student. Speak entirely as {persona['name']}, in the first "
        "person.\n\n"
        f"YOUR CHARACTER: {persona['style']}\n\n"
        "HOW YOU DELIVER A LECTURE:\n"
        "- Warm, expert and conversational, as if talking one-to-one. This is a "
        "monologue you speak aloud, not a written article.\n"
        "- NEVER ask the student a question — not rhetorical ones, not "
        "'can you see why?', not 'make sense?'. You are lecturing, not "
        "conversing. The student can interrupt to ask you things separately.\n"
        "- Signpost naturally as you go ('Let's start with…', 'Now that that's "
        "clear…', 'The key thing to remember here…', 'Finally…') so the student "
        "always knows where they are.\n"
        "- Pace yourself: introduce one idea at a time, build on it, and pause "
        "on the points that matter most for the exam.\n"
        "- Teach with concrete examples and everyday analogies, not abstract "
        "definitions alone.\n\n"
        f"LENGTH: roughly {spec['words']} words, which is {spec['label']} when "
        "spoken aloud. Cover the topic to that depth — don't pad, don't rush.\n\n"
        "OUTPUT FORMAT (this is read straight into text-to-speech):\n"
        "- Write only the spoken script — no headings, bullet points, markdown, "
        "numbered lists, stage directions, speaker labels or '[pause]' markers. "
        "None of that can be spoken.\n"
        "- Use British spelling."
    )


def _prompt(domain: dict[str, Any], module: dict[str, Any], length: str) -> str:
    """The per-lecture task: what this specific lecture is about."""
    subject = module.get("detected_subject") or module.get("title") or "this subject"
    context = (module.get("course_context") or "").strip()
    weight = domain.get("weight_pct")

    return (
        f"Deliver your lecture on this topic.\n\n"
        f"SUBJECT: {subject}\n"
        f"TOPIC: {domain.get('title')}\n"
        + (f"TOPIC SCOPE: {domain.get('description')}\n" if domain.get("description") else "")
        + (f"This topic is {weight}% of the exam, so weight your depth accordingly.\n"
           if weight else "")
        + (f"\nThe learner's own course syllabus, for alignment:\n{context[:4000]}\n"
           if context else "")
        + "\nOpen by naming the topic and why it matters for the exam, teach it "
        "in a logical build-up, call out the points most likely to be examined, "
        "and close with a short recap of the key takeaways."
    )


def generate_text(lecture_id: str, domain: dict[str, Any], module: dict[str, Any],
                  length: str, voice: str = "marcus") -> str:
    """Stream the lecture script from Gemini, persisting and publishing deltas.

    The tutor persona is the system instruction; the specific topic is the user
    prompt. Returns the full transcript. Partial text is saved continuously, so
    an interrupted run still leaves recoverable content.
    """
    if not settings.gemini_api_key:
        raise LectureGenerationError("GEMINI_API_KEY is not configured.")

    from google import genai
    from google.genai import types

    # Its own client with a longer leash than the shared 30s: a full lecture
    # script streams for well over a minute legitimately, and killing it at the
    # question-generation deadline would break every long lecture. Streaming is
    # also its own liveness signal — chunks either arrive or the read times out.
    client = genai.Client(
        api_key=settings.gemini_api_key,
        http_options=types.HttpOptions(timeout=180_000),
    )
    channel = f"lecture:{lecture_id}"
    parts: list[str] = []
    pending = 0

    _update(lecture_id, {"status": "generating_text", "transcript": ""})
    broadcast.publish(channel, {"event": "status", "data": {"status": "generating_text"}})

    try:
        stream = client.models.generate_content_stream(
            model=settings.gemini_model,
            contents=_prompt(domain, module, length),
            config=types.GenerateContentConfig(
                system_instruction=_system_instruction(voice, length),
                temperature=0.7,
            ),
        )
        for piece in stream:
            delta = piece.text or ""
            if not delta:
                continue
            parts.append(delta)
            pending += len(delta)
            broadcast.publish(channel, {"event": "delta", "data": {"text": delta}})

            # Persist periodically rather than per-token — enough for a
            # reconnecting client to catch up without hammering the database.
            if pending >= 600:
                _update(lecture_id, {"transcript": "".join(parts)})
                pending = 0
    except Exception as exc:  # noqa: BLE001
        message = quota_hint(exc) or f"Lecture text generation failed: {exc}"
        raise LectureGenerationError(message) from exc

    transcript = _clean("".join(parts))
    if len(transcript) < 200:
        raise LectureGenerationError(
            "The model returned too little text to build a lecture from."
        )

    _update(
        lecture_id,
        {"transcript": transcript, "word_count": len(transcript.split())},
    )
    return transcript


def _clean(text: str) -> str:
    """Strip artefacts that would be read aloud verbatim."""
    text = re.sub(r"^\s*#{1,6}\s*", "", text, flags=re.MULTILINE)   # headings
    text = re.sub(r"\*{1,3}([^*]+)\*{1,3}", r"\1", text)            # bold/italic
    text = re.sub(r"^\s*[-*•]\s+", "", text, flags=re.MULTILINE)    # bullets
    text = re.sub(r"\[(pause|beat|music)[^\]]*\]", "", text, flags=re.I)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


# --- Audio generation -------------------------------------------------------
def split_for_tts(text: str, limit: int = TTS_CHUNK_CHARS) -> list[str]:
    """Split a script into TTS-sized pieces without cutting mid-sentence."""
    if len(text) <= limit:
        return [text]

    sentences = re.split(r"(?<=[.!?])\s+", text)
    chunks: list[str] = []
    buffer = ""

    for sentence in sentences:
        # A single sentence longer than the cap is split on whitespace.
        while len(sentence) > limit:
            cut = sentence.rfind(" ", 0, limit)
            cut = cut if cut > 0 else limit
            if buffer:
                chunks.append(buffer.strip())
                buffer = ""
            chunks.append(sentence[:cut].strip())
            sentence = sentence[cut:].lstrip()

        if len(buffer) + len(sentence) + 1 > limit:
            chunks.append(buffer.strip())
            buffer = sentence
        else:
            buffer = f"{buffer} {sentence}".strip()

    if buffer.strip():
        chunks.append(buffer.strip())
    return [c for c in chunks if c]


def estimate_duration(text: str) -> int:
    """Estimated spoken length in seconds.

    An estimate, not a measurement — decoding every MP3 to read its true
    duration would cost more than it's worth here. Playback position is tracked
    by the audio element itself, so this is only used for display.
    """
    return max(1, round(len(text.split()) / WORDS_PER_MINUTE * 60))


def generate_audio(lecture_id: str, user_id: str, transcript: str,
                   voice: str) -> tuple[list[dict[str, Any]], int]:
    """TTS the transcript into cached Storage objects.

    Returns ``(chunks, total_duration_secs)``. Raises if any chunk fails —
    a lecture with holes in its audio is worse than a clear failure.
    """
    if not settings.openai_api_key:
        raise LectureGenerationError(
            "Audio narration needs OPENAI_API_KEY to be configured."
        )

    from openai import OpenAI

    from app.services.extraction import _transcription_error

    client = OpenAI(api_key=settings.openai_api_key)
    openai_voice = resolve_voice(voice)
    pieces = split_for_tts(transcript)
    channel = f"lecture:{lecture_id}"
    storage = get_supabase().storage.from_(settings.lecture_audio_bucket)

    _update(lecture_id, {"status": "generating_audio"})
    broadcast.publish(channel, {
        "event": "status",
        "data": {"status": "generating_audio", "chunks": len(pieces)},
    })

    chunks: list[dict[str, Any]] = []
    total = 0

    for index, piece in enumerate(pieces):
        try:
            response = client.audio.speech.create(
                model=settings.openai_tts_model,
                voice=openai_voice,
                input=piece,
                response_format="mp3",
            )
            audio = response.content
        except Exception as exc:  # noqa: BLE001
            raise LectureGenerationError(_transcription_error(exc)) from exc

        path = f"{user_id}/{lecture_id}/{index:03d}.mp3"
        try:
            storage.upload(
                path=path,
                file=audio,
                file_options={"content-type": "audio/mpeg", "upsert": "true"},
            )
        except Exception as exc:  # noqa: BLE001
            raise LectureGenerationError(f"Could not cache audio chunk: {exc}") from exc

        seconds = estimate_duration(piece)
        total += seconds
        chunks.append({
            "index": index,
            "storage_path": path,
            "chars": len(piece),
            "duration_secs": seconds,
            "bytes": len(audio),
        })

        _update(lecture_id, {"audio_chunks": chunks})
        broadcast.publish(channel, {
            "event": "audio_chunk",
            "data": {"index": index, "of": len(pieces), "duration_secs": seconds},
        })
        logger.info("Lecture %s: audio chunk %d/%d cached",
                    lecture_id, index + 1, len(pieces))

    return chunks, total


# --- Orchestration ----------------------------------------------------------
def generate_lecture(lecture_id: str, user_id: str, domain: dict[str, Any],
                     module: dict[str, Any], length: str, voice: str) -> dict[str, Any]:
    """Full §4.4 generation. Safe to run as a background task."""
    channel = f"lecture:{lecture_id}"
    try:
        transcript = generate_text(lecture_id, domain, module, length, voice)
        chunks, duration = generate_audio(lecture_id, user_id, transcript, voice)

        _update(lecture_id, {
            "status": "ready",
            "audio_chunks": chunks,
            "duration_secs": duration,
            "audio_url": chunks[0]["storage_path"] if chunks else None,
            "generated_at": _now_iso(),
            "error_message": None,
        })
        broadcast.publish(channel, {
            "event": "complete",
            "data": {"duration_secs": duration, "chunks": len(chunks),
                     "word_count": len(transcript.split())},
        })
        logger.info("Lecture %s ready: %d chunks, ~%ds", lecture_id, len(chunks), duration)
        return {"status": "ready", "duration_secs": duration, "chunks": len(chunks)}

    except LectureGenerationError as exc:
        logger.error("Lecture %s failed: %s", lecture_id, exc)
        _update(lecture_id, {"status": "failed", "error_message": str(exc)[:1000]})
        broadcast.publish(channel, {"event": "error", "data": {"message": str(exc)}})
        return {"status": "failed", "error": str(exc)}
    except Exception as exc:  # noqa: BLE001 - a background task must not escape
        logger.exception("Lecture %s crashed", lecture_id)
        _update(lecture_id, {"status": "failed", "error_message": str(exc)[:1000]})
        broadcast.publish(channel, {"event": "error", "data": {"message": str(exc)}})
        return {"status": "failed", "error": str(exc)}
